
VERSION = LCMS_VERSION
D50X = cmsD50X
D50Y = cmsD50Y
D50Z = cmsD50Z
PERCEPTUAL_BLACK_X = cmsPERCEPTUAL_BLACK_X
PERCEPTUAL_BLACK_Y = cmsPERCEPTUAL_BLACK_Y
PERCEPTUAL_BLACK_Z = cmsPERCEPTUAL_BLACK_Z
MAXCHANNELS = cmsMAXCHANNELS
